name: Unit Tests

on:
    push:
    pull_request:
        branches: [ "main" ]

jobs:
    build-and-test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                arch: [ x64, arm64 ]
                config: [ release ]

        steps:
            - name: Checkout source
              uses: actions/checkout@v3
              with:
                submodules: 'recursive'
                fetch-depth: 1

            - name: Configure
              shell: bash
              run: |
                cmake --preset release

            - name: Build
              shell: bash
              run: |
                cmake --build --preset release

            - name: Test (Unit)
              shell: bash
              run: |
                ctest --preset release

            - name: Test (Smoke)
              shell: bash
              run: |
                cmake --build --preset release --target smoke_test
