name: Unit

on:
    push:
    pull_request:
        branches: [ "main" ]

jobs:
    build-and-test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                arch: [ x64, arm64 ]
                config: [ release ]

        steps:
            - name: Checkout source
              uses: actions/checkout@v3

            - name: Set PLATFORM variable
              shell: bash
              run: |
                if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                    echo "PLATFORM=apple" >> $GITHUB_ENV
                elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                    echo "PLATFORM=linux" >> $GITHUB_ENV
                else
                    echo "PLATFORM=windows" >> $GITHUB_ENV

            - name: Configure
              run: |
                cmake --preset "${{ matrix.arch }}-${PLATFORM}"

            - name: Build
              run: |
                cmake --build --preset "${{ matrix.arch }}-${PLATFORM}-${{ matrix.config }}"

            - name: Test
              run: |
                ctest --preset "${{ matrix.arch }}-${PLATFORM}-${{ matrix.config }}"
